services:
  mln111:
    image: hoangworthy/mln111:latest
    container_name: mln111
    restart: always
    ports:
      - "25577:25577"
      - "25578:25578"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-25578}
      - CLIENT_PORT=${CLIENT_PORT:-25577}
      - CLIENT_URL=https://mnl111.bughunters.site:25577
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL:-https://mnl111-api.bughunters.site:25578}
    networks:
      - mln111-network

networks:
  mln111-network:
    driver: bridge
